### ISSUE TITLE
Fails to run "mix setup" on Elixir 1.7.4

### ISSUE THREAD

**Issue by streamerd** [iamucil/elixir-webrtc#2]
Hi,

Project is not seting up or install deps. Getting the same error for both.

λ  elixir-webrtc git:(master) **elixir -v**
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

**Elixir 1.7.4 (compiled with Erlang/OTP 21)**

==== step to reproduce (running the command on project's root) =====
λ  elixir-webrtc git:(master) **mix setup**
** (MatchError) no match of right hand side value: []
    (elixir) lib/code.ex:232: Code.eval_string/3
    (mix) lib/mix/config.ex:220: Mix.Config.eval!/2
    (mix) lib/mix/tasks/loadconfig.ex:37: Mix.Tasks.Loadconfig.load/1
    (mix) lib/mix/tasks/loadconfig.ex:27: Mix.Tasks.Loadconfig.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:78: Mix.CLI.run_task/2

======================================================

**Comment by iamucil** [comment]
@streamerd you can use docker container and run inside container, or just build docker image using `Dockerfile` from this repo, and run

**Comment by streamerd** [comment]
@iamucil tried with docker, 

The app runs on localhost:5000, connected to psql as well; yet buttons are unresponsive. 

The request url contains an undefined value too.
ws://localhost:5000/socket/websocket?token=**undefined**&vsn=2.0.0



`$ docker-compose up --build --abort-on-container-exit --remove-orphans
`
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                    NAMES
9b651d4e1a59        elixir-webrtc_phx-webrtc-site   "mix phx.server"         19 minutes ago      Up 44 seconds       0.0.0.0:5000->5000/tcp   elixir-webrtc_phx-webrtc-site_1
a6248e48c43e        postgres:10.7-alpine            "docker-entrypoint.s…"   19 minutes ago      Up 44 seconds       0.0.0.0:6432->5432/tcp   elixir-webrtc_phx-webrtc-db_1

```

phoenix app logs:

```
phx-webrtc-site_1  | [error] Ranch listener PHXWebRTCWeb.Endpoint.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.868.0> exit with reason: {:undef, [{PHPWebRTCWeb.CallChannel, :child_spec, [{%{}, {#PID<0.868.0>, #Reference<0.2478714349.1721237505.182939>}, %Phoenix.Socket{assigns: %{}, channel: PHPWebRTCWeb.CallChannel, channel_pid: nil, endpoint: PHXWebRTCWeb.Endpoint, handler: PHXWebRTCWeb.UserSocket, id: nil, join_ref: "105", joined: false, private: %{}, pubsub_server: PHXWebRTC.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "call", transport: :websocket, transport_pid: #PID<0.868.0>}}], []}, {Phoenix.Channel.Server, :join, 4, [file: 'lib/phoenix/channel/server.ex', line: 25]}, {Phoenix.Socket, :handle_in, 4, [file: 'lib/phoenix/socket.ex', line: 617]}, {Phoenix.Endpoint.Cowboy2Handler, :websocket_handle, 2, [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 174]}, {:cowboy_websocket, :handler_call, 6, [file: '/opt/app/deps/cowboy/src/cowboy_websocket.erl', line: 482]}, {:cowboy_http, :loop, 1, [file: '/opt/app/deps/cowboy/src/cowboy_http.erl', line: 231]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
phx-webrtc-site_1  |
phx-webrtc-site_1  | [info] CONNECTED TO PHXWebRTCWeb.UserSocket in 260µs
phx-webrtc-site_1  |   Transport: :websocket
phx-webrtc-site_1  |   Serializer: Phoenix.Socket.V2.JSONSerializer
phx-webrtc-site_1  |   Parameters: %{"token" => "undefined", "vsn" => "2.0.0"}
phx-webrtc-site_1  | [error] Ranch listener PHXWebRTCWeb.Endpoint.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.871.0> exit with reason: {:undef, [{PHPWebRTCWeb.CallChannel, :child_spec, [{%{}, {#PID<0.871.0>, #Reference<0.2478714349.1721237505.183220>}, %Phoenix.Socket{assigns: %{}, channel: PHPWebRTCWeb.CallChannel, channel_pid: nil, endpoint: PHXWebRTCWeb.Endpoint, handler: PHXWebRTCWeb.UserSocket, id: nil, join_ref: "106", joined: false, private: %{}, pubsub_server: PHXWebRTC.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "call", transport: :websocket, transport_pid: #PID<0.871.0>}}], []}, {Phoenix.Channel.Server, :join, 4, [file: 'lib/phoenix/channel/server.ex', line: 25]}, {Phoenix.Socket, :handle_in, 4, [file: 'lib/phoenix/socket.ex', line: 617]}, {Phoenix.Endpoint.Cowboy2Handler, :websocket_handle, 2, [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 174]}, {:cowboy_websocket, :handler_call, 6, [file: '/opt/app/deps/cowboy/src/cowboy_websocket.erl', line: 482]}, {:cowboy_http, :loop, 1, [file: '/opt/app/deps/cowboy/src/cowboy_http.erl', line: 231]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
```



Request URL appearing as: 

ws://localhost:5000/socket/websocket?token=**undefined**&vsn=2.0.0

within the Web socket messages,
```
["14", "14", "phoenix:live_reload", "phx_reply",…]
0: "14"
1: "14"
2: "phoenix:live_reload"
3: "phx_reply"
4: {response: {message: "live reload backend not running"}, status: "error"}
```

**Comment by vimalMK** [comment]
@iamucil  
 I am having the exact same issue. Please advice.
